/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    A: typeof import('./components/A.vue')['default']
    B: typeof import('./components/B.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    C: typeof import('./components/C.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    ElButton: typeof import('element-plus')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus')['ElDatePicker']
    ElIcon: typeof import('element-plus')['ElIcon']
    ElInput: typeof import('element-plus')['ElInput']
    ElMenu: typeof import('element-plus')['ElMenu']
    ElMenuItem: typeof import('element-plus')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus')['ElSubMenu']
    ElTag: typeof import('element-plus')['ElTag']
    Father: typeof import('./components/deliver/Father.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    Son: typeof import('./components/deliver/Son.vue')['default']
    Tree: typeof import('./components/Tree.vue')['default']
    Up: typeof import('./components/deliver/Up.vue')['default']
  }
}
